//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendShip
    {
        public System.Guid ID { get; set; }
        public System.Guid UID { get; set; }
        public System.Guid FriendID { get; set; }
        public string Remark { get; set; }
        public int Ignore { get; set; }
        public int IsTop { get; set; }
        public int IsDel { get; set; }
        public int IsBlack { get; set; }
        public Nullable<System.Guid> LastMID { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> lastReadID { get; set; }
    }
}
