//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCZoneComment
    {
        public System.Guid ID { get; set; }
        public System.Guid GCZID { get; set; }
        public Nullable<System.Guid> ReplyID { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.Guid UID { get; set; }
        public string Content { get; set; }
    
        public virtual GCZone GCZone { get; set; }
    }
}
