//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Infomations
    {
        public System.Guid IID { get; set; }
        public System.Guid UID { get; set; }
        public int Type { get; set; }
        public string title { get; set; }
        public string imglist { get; set; }
        public string LinkTo { get; set; }
        public int ViewCount { get; set; }
        public int GoodCount { get; set; }
        public Nullable<decimal> AreaX { get; set; }
        public Nullable<decimal> AreaY { get; set; }
        public Nullable<int> AreaLimit { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
