//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public System.Guid ID { get; set; }
        public System.Guid ProductID { get; set; }
        public string Number { get; set; }
        public string SpecificationAttr { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public decimal Stock { get; set; }
        public decimal SellCount { get; set; }
        public Nullable<int> Integral { get; set; }
        public Nullable<decimal> IntegralPrice { get; set; }
        public Nullable<int> IntegralSalesVolume { get; set; }
    }
}
